### ISSUE TITLE
cannot overwrite a file with `-o` set

### ISSUE THREAD

**Issue by Hunam6** [vlang/go2v#23]
Same as #18 but only when `-o` is specified.
Steps to reproduce:
```
touch file.go // file.go gets created
v run . file.go -o out.v // out.v gets created
v run . file.go -o out.v //error
```
I get `cli execution error: failed to open file "out.v/out.v"`

**Comment by JalonSolov** [comment]
Hmm... I get a completely different error...
```
$ touch file.go
$ v run . file.go -o out.v
$ v run . file.go -o out.v
./out.v:2:1: error: unexpected eof, expecting name
    1 | module
$
```
If I have a non-empty `file.go` (at least `package main` line at the top), then I get the same error you see, on the 2nd run.

**Comment by JalonSolov** [comment]
Paths are tricky... especially when V is missing several fairly basic routines to deal with them.  :-(

I think I have a fix, if I can just implement it around those missing pieces.

**Comment by JalonSolov** [comment]
The PR fixes this specific case, along with several others I found while testing.  Things like having input be a dir, but setting output to an existing file.  It now gives an error message.  Or setting output to a directory where you don't have write permissions will now give a permissions error instead of silently appearing to work... but no output being created.
